replicaCount: 1

image:
  repository: public.ecr.aws/h3n1a7z5/netflix-clone  # Replace with your ECR repository URL
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  # Add your ingress configurations here
